# Generated by Django 4.1.4 on 2023-01-15 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ADBMS', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
